# Test $d

name: Test

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - name: Cpan
      run:  sudo cpan install -T Data::Dump
    - name: Ubuntu update
      run:  sudo apt update

    - name: Verilog
      run:  sudo apt -y install iverilog

    - name: Verilog Version
      run:  iverilog -V

    - name: Yosys
      run:  wget -q https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-06-14/oss-cad-suite-linux-x64-20230614.tgz

    - name: Yosys unzip
      run: gunzip  oss-cad-suite-linux-x64-20230614.tgz

    - name: Yosys untar
      run: tar -xf oss-cad-suite-linux-x64-20230614.tar

    - name: Yosys_Add_
      if: ${{ always() }}
      run: |
        export PATH="$PATH:$GITHUB_WORKSPACE/oss-cad-suite/bin/"
        yosys -d -Q -p "read_verilog -nomem2reg verilog/fpga/tests/Add/fpga.sv; synth_gowin -noflatten -nodffe -top fpga -json verilog/fpga/tests/Add/fpga.json"
