# Test 2023-07-17 at 00:06:32

name: Test

on:
  push:
    paths:
      - '**.pm'
      - '**pushToGitHub.pl'
      - '**.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - name: Cpan
      run:  sudo cpan install -T Data::Dump
    - name: Ubuntu update
      run:  sudo apt update

    - name: Verilog
      run:  sudo apt -y install iverilog

    - name: Verilog Version
      run:  iverilog -V

    - name: Emulator
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib lib/Zero/Emulator.pm

    - name: BubbleSort
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib examples/bubbleSort.pl

    - name: InsertionSort
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib examples/insertionSort.pl

    - name: QuickSort
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib examples/quickSort.pl

    - name: QuickSort Parallel
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib examples/quickSortParallel.pl

    - name: SelectionSort
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib examples/selectionSort.pl

    - name: TestEmulator
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib examples/testEmulator.pl

    - name: BTree
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib lib/Zero/BTree.pm

    - name: TestBTree - last as it is longest
      run:  perl -I$GITHUB_WORKSPACE/dtt/lib examples/testBTree.pl

  fpga:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - name: Cpan
      run:  sudo cpan install -T Data::Dump
    - name: Ubuntu update
      run:  sudo apt update

    - name: Verilog
      run:  sudo apt -y install iverilog

    - name: Verilog Version
      run:  iverilog -V
    - name: verilog/fpga/tests/ArrayAdd/fpga.sv
      if: ${{ always() }}
      run: |
        rm -f fpga z1.txt; iverilog -Iverilog/includes -g2012 -o fpga verilog/fpga/tests/ArrayAdd/fpga.tb verilog/fpga/tests/ArrayAdd/fpga.sv && timeout 1m ./fpga | tee z1.txt; grep -qv "FAILED" z1.txt


  Yosys_ArrayAdd_:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - name: Cpan
      run:  sudo cpan install -T Data::Dump
    - name: Yosys
      run:  wget -q https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-06-14/oss-cad-suite-linux-x64-20230614.tgz

    - name: Yosys unzip
      run: gunzip  oss-cad-suite-linux-x64-20230614.tgz

    - name: Yosys untar
      run: tar -xf oss-cad-suite-linux-x64-20230614.tar

    - name: Yosys_ArrayAdd_
      if: ${{ always() }}
      run: |
        export PATH="$PATH:$GITHUB_WORKSPACE/oss-cad-suite/bin/"
        yosys -d -Q -p "read_verilog verilog/fpga/tests/ArrayAdd/fpga.sv; synth_gowin -top fpga -json verilog/fpga/tests/ArrayAdd/fpga.json"

    - name: NextPnr_ArrayAdd_
      if: ${{ always() }}
      run: |
        export PATH="$PATH:$GITHUB_WORKSPACE/oss-cad-suite/bin/"
        nextpnr-gowin --json verilog/fpga/tests/ArrayAdd/fpga.json --write verilog/fpga/tests/ArrayAdd/fpga.pnr --device "GW1NR-LV9QN88PC6/I5" --family GW1N-9C --cst verilog/fpga/tests/ArrayAdd/tangnano9k.cst

    - name: Pack_ArrayAdd_
      if: ${{ always() }}
      run: |
        export PATH="$PATH:$GITHUB_WORKSPACE/oss-cad-suite/bin/"
        gowin_pack -d GW1N-9C -o verilog/fpga/tests/ArrayAdd/fpga.fs verilog/fpga/tests/ArrayAdd/fpga.pnr

    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        path: verilog/fpga/tests/ArrayAdd/

